source 'https://rubygems.org'
ruby '2.0.0'

gem 'sinatra', :github => 'sinatra/sinatra'
gem 'json'
gem 'pry'
gem 'pg'
gem 'dm-postgres-adapter'
gem 'data_mapper'
gem 'puma'
gem 'sanitize'
gem 'dm-serializer'